### ISSUE TITLE
V00 - TODO before merge

### ISSUE THREAD

**Issue by florisa** [florisa/MaterialDataForAbaqusGUI#1]
# TODO List:
## Manual Plot function
- [x]  https://www.mathworks.com/help/matlab/ref/linspace.html

- [x] Legend must be hidden for large number of Epsilons

- [x] Legend location shifts to the left side

**Comment by florisa** [comment]
done!
